### ISSUE TITLE
This cannot work anywhere else, the only function it does is print the definition

### ISSUE THREAD

**Issue by InvisibleOS** [nit-in/py-dictionary#3]
I am unable to use the definition anywhere else. I am currently using this in discord.py where I want to send this meaning as a text message but instead, it prints the meaning.

**Comment by nit-in** [comment]
update the module it should work fine now

pip install --upgrade Py-Dictionary 

The results like meaning, synonyms and antonyms are now returned as list
so use can use them without printing them.

for example 

`from pydictionary import Dictionary`

`dict = Dictionary("fix")`

### enter the word you want to search here e.g. I used the word "fix"
### To get the result as list do following 

`meanings_list = dict.meaning()`

`synonyms_list = dict.synonyms()`

`antonyms_list = dict.antonyms()`

you can use them in your program as list

check the README.md also
